stages:
  - build
  - deploy-staging
  - deploy-sandbox

build:
  image: node:carbon-alpine
  stage: build
  only:
    - develop
    - master
  artifacts:
    untracked: true
  script:
    - if [ "$CI_COMMIT_REF_NAME" == "develop" ]; then cp .env.staging .env; fi
    - if [ "$CI_COMMIT_REF_NAME" == "master" ]; then cp .env.staging .env; fi
    - npm install
    - unset CI
    - npm run build

deploy-staging:
  image: google/cloud-sdk:alpine
  stage: deploy-staging
  only:
    - master
  dependencies:
    - build
  script:
    - echo $STAGING_SERVICE_ACCOUNT > service-account.json
    - gcloud auth activate-service-account --key-file service-account.json
    # TODO: For now master brand deploy to production, its will be change when we create staging environment
    - gcloud --quiet --project $STAGING_PROJECT_ID app deploy app-production.yaml
  after_script:
    - rm -rf service-account.json